### ISSUE TITLE
Fixtures fails on startup sometimes

### ISSUE THREAD

**Issue by chatch** [zulucrypto/docker-stellar-integration-test-network#1]
Sometimes fixtures completes and some times it fails:

INFO exited: fixtures (exit status 22; not expected)

I can't tell why this is happening but restarting a few times I can usually get it to complete.

**Comment by chatch** [comment]
There is a timeout from the fixtures:

"curl: (22) The requested URL returned error: 500 Internal Server Error"

which I think is from this curl to the bridge:

curl --fail -X POST http://localhost:8006/payment \
    -d "amount=10000000&destination=GCRJYNHOL62AZNGZQCLAVP4WW26JD5FLG2PPIKC5T3YR42NQJJJ7LK4Q"

which triggers a /transactions call to horizon that ends in this:

time="2017-11-10T10:37:06Z" level=info msg="Finished request" bytes=234 duration=30.000443268s host="localhost:8000" ip="127.0.0.1:32876" method=POST path="/transactions" pid=175 req="22d1bb3567db/OmiWqbuBcJ-000006" status=504 streaming=false

**Comment by zulucrypto** [comment]
Thanks for the details about when it fails. I've seen this occasionally as well, but so far haven't been able to track it down. I'm planning on upgrading the stellar-core version to 9.0.1 soon and will put some more effort into figuring out a fix.

**Comment by zulucrypto** [comment]
@chatch - I believe this was happening because Horizon was starting before stellar core was fully synced.

I've been running locally with a fix and haven't seen fixtures fail recently, so I'm hoping this is resolved. Please re-open this issue or log a new one if you see similar behavior going forward!

**Comment by chatch** [comment]
ok thanks @zulucrypto. i'll be running this again soon so I'll grab the latest and try.
