### ISSUE TITLE
components update

### ISSUE THREAD

**Issue by bolshoy** [zulucrypto/docker-stellar-integration-test-network#3]
you might want to update the component versions:
- up to date Horizon is 0.11.1
- up to date Bridge is 0.0.30

Currently some Horizon endpoints (`/trades` and `/assets`) are not working.

**Comment by zulucrypto** [comment]
Thanks for the reminder! I upgraded these components but hit the following issue: https://github.com/stellar/bridge-server/issues/98

Once I figure out how to work around that, I'll update the components here.

**Comment by zulucrypto** [comment]
I've pushed v1.9.2 of the docker container with Horizon 0.11.1 and Bridge 0.0.30

**Comment by bolshoy** [comment]
i suggest to print the versions when the container starts, so you won't have to check the repo

**Comment by zulucrypto** [comment]
@bolshoy - Great idea, I've added the versions to the startup message
