### ISSUE TITLE
horizon upgrade

### ISSUE THREAD

**Issue by bolshoy** [zulucrypto/docker-stellar-integration-test-network#4]
@zulucrypto you might want to upgrade the container with a current Horizon release, which is 0.12.3.
See https://github.com/stellar/go/releases
Mind that the Friendbot is a separate service now, not a part of Horizon anymore.

**Comment by zulucrypto** [comment]
Hi @bolshoy - 0.12.3 has moved friendbot to a standalone service. I'm currently tracking down a friendbot release and I'll work on getting it integrated into the docker container.

**Comment by collinjackson** [comment]
Friendbot has been released https://github.com/stellar/go/releases/tag/friendbot-v0.0.1

**Comment by zulucrypto** [comment]
@collinjackson - Thanks for the heads up about Friendbot.

I've pushed container version 1.10.1 with the latest version of Horizon and Stellar Core
