### ISSUE TITLE
Change version Postgres from 9.4 to 9.6 

### ISSUE THREAD

**Issue by rchatsiri** [zulucrypto/docker-stellar-integration-test-network#5]
Start script used version 9.4. Now same apt package changed to version 9.6. 

Path PGING: /usr/lib/postgresql/9.4/bin compares /usr/lib/postgresql/9.6/bin

Can you update a part of Postgres script in master branch from 9.4 to 9.6?

**Comment by aph5nt** [comment]
pls do so

**Comment by zulucrypto** [comment]
Postgres has been upgraded to 9.6 as of container version 1.10.1
