### ISSUE TITLE
STELLAR/BRIDGE version update HORIZON download location changed

### ISSUE THREAD

**Issue by Gershon-A** [zulucrypto/docker-stellar-integration-test-network#6]
Hello,
New version as following 
ENV STELLAR_CORE_VERSION 9.2.0-551-7561c1d5
ENV HORIZON_VERSION 0.13.0
ENV BRIDGE_VERSION 0.0.31

The HORIZON download location was changed, so new downloaded path is:
`wget -O horizon.tar.gz https://github.com/stellar/go/releases/download/horizon-v${HORIZON_VERSION}/horizon-v${HORIZON_VERSION}-linux-amd64.tar.gz`
P.S is some one interested , i update existing running docker as following:
`export STELLAR_CORE_VERSION=9.2.0-551-7561c1d5
`
Run update:
```
wget -O stellar-core.deb https://s3.amazonaws.com/stellar.org/releases/stellar-core/stellar-core-${STELLAR_CORE_VERSION}_amd64.deb \
&& dpkg -i stellar-core.deb \
&& rm stellar-core.deb \
```
`export HORIZON_VERSION=0.13.0
`
Run update:
```
wget -O horizon.tar.gz https://github.com/stellar/go/releases/download/horizon-v${HORIZON_VERSION}/horizon-v${HORIZON_VERSION}-linux-amd64.tar.gz \
    && tar -zxvf horizon.tar.gz \
    && mv /horizon-v${HORIZON_VERSION}-linux-amd64/horizon /usr/local/bin \
    && chmod +x /usr/local/bin/horizon \
    && rm -rf horizon.tar.gz /horizon-v${HORIZON_VERSION}-linux-amd64 \
```
`export BRIDGE_VERSION=0.0.31
`
Run update:
```
curl -L https://github.com/stellar/bridge-server/releases/download/v${BRIDGE_VERSION}/bridge-v${BRIDGE_VERSION}-linux-amd64.tar.gz \
        | tar -xz -C /opt/stellar/bridge --strip-components=1 \
```

**Comment by zulucrypto** [comment]
Core, Horizon, and Bridge have been upgraded to the latest versions.
